baseURL = "https://antoniofagardo.github.io/"
languageCode = "en-us"
title = "Our Best Recipes"
theme = "arabica"
paginate = 3
staticDir = "static"

author = "Antoine Gosset"
authorWebsite = ""
authorDescription = "Coder, Developper"


[permalinks]
    post = "/post/:slug/"

[params]
    description = "By Antoine & Laila"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"

[[menu.main]]
    name = "Food"
    url = "/tags/food"
    weight = 20

[[menu.main]]
    name = "Development"
    url = "/tags/development"
    weight = 80

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
